# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78d55560f2bd839662c54af3b95adca9660b7fc5fa464b6bca35eab0d411f3f1625bcdb70342fc3ec8ecbbaf54d3cddbd6fee6bf505c2027350a5e223fd786d0

test:
  secret_key_base: 66599b84625a581a9be72620ecd4621b1a5f9ed0b748694e9f0d4f87d7a27511562618be90b5b6931d36865dbabe14abb5f31e840e5aa7c2ce4366e7e6d09f73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
